import CustomAddresses from './custom-addresses.svg';
import CustomBasket from './custom-basket.svg';
import CustomCalendarAdd from './custom-calendar-add.svg';
import CustomCalendar from './custom-calendar.svg';
import CustomChart from './custom-chart.svg';
import CustomEditReview from './custom-edit-review.svg';
import CustomHelp from './custom-help.svg';
import CustomInvoiceDownload from './custom-invoice-download.svg';
import CustomMessages from './custom-messages.svg';
import CustomOrders from './custom-orders.svg';
import CustomPayments from './custom-payments.svg';
import CustomReferrals from './custom-referrals.svg';
import CustomRefund from './custom-refund.svg';
import CustomRepeat from './custom-repeat.svg';
import CustomSecurity from './custom-security.svg';

export const CustomAddressesSvg = CustomAddresses;
export const CustomBasketSvg = CustomBasket;
export const CustomCalendarAddSvg = CustomCalendarAdd;
export const CustomCalendarSvg = CustomCalendar;
export const CustomChartSvg = CustomChart;
export const CustomEditReviewSvg = CustomEditReview;
export const CustomHelpSvg = CustomHelp;
export const CustomInvoiceDownloadSvg = CustomInvoiceDownload;
export const CustomMessagesSvg = CustomMessages;
export const CustomOrdersSvg = CustomOrders;
export const CustomPaymentsSvg = CustomPayments;
export const CustomReferralsSvg = CustomReferrals;
export const CustomRefundSvg = CustomRefund;
export const CustomRepeatSvg = CustomRepeat;
export const CustomSecuritySvg = CustomSecurity;