const allRoles = {
  user: [
    'manageBaskets',
    'getBaskets',
    'getAddresses',
    'manageAddresses',
    'getBalances',
    'manageBalances',
    'getCategories',
    'manageCategories',
    'getFees',
    'manageFees',
    'getDeliveryEstimates',
    'manageDeliveryEstimates',
    'getPayments',
    'managePayments',
    'getMessages',
    'manageMessages',
    'getProducts',
    'manageProducts',
    'getMessageDetails',
    'manageMessageDetails',
    'getLocations',
    'manageLocations',
    'getOrders',
    'manageOrders',
    'getOrderDetails',
    'manageOrderDetails',
    'getMessageDetails',
    'manageMessageDetails',
    'getReorders',
    'manageReorders',
    'getReviews',
    'manageReviews',
    'getTaxIds',
    'manageTaxIds',
    'getCountry'
  ],
  admin: ['getUsers', 'manageUsers', 'getLocations', 'manageLocations'],
  business: [
    'manageBaskets',
    'getBaskets',
    'getAddresses',
    'manageAddresses',
    'getBalances',
    'manageBalances',
    'getCategories',
    'manageCategories',
    'getFees',
    'manageFees',
    'getDeliveryEstimates',
    'manageDeliveryEstimates',
    'getPayments',
    'managePayments',
    'getMessages',
    'manageMessages',
    'getProducts',
    'manageProducts',
    'getMessageDetails',
    'manageMessageDetails',
    'getLocations',
    'manageLocations',
    'getOrders',
    'manageOrders',
    'getOrderDetails',
    'manageOrderDetails',
    'getMessageDetails',
    'manageMessageDetails',
    'getReorders',
    'manageReorders',
    'getReviews',
    'manageReviews',
    'getTaxIds',
    'manageTaxIds',
    'getCountry'
  ],
};

const roles = Object.keys(allRoles);
const roleRights = new Map(Object.entries(allRoles));

module.exports = {
  roles,
  roleRights,
};
